BookMyComics-Developers/BookMyComics

- web-extensions/chrome/storage.js
Just saw this while quickly reading through the code ;)
> Fixed incorrect JSdoc syntax

- browsers/chrome.json
- browsers/firefox.json
- web-extensions/chrome/background-engine.js
- web-extensions/chrome/compat.js
- web-extensions/chrome/engine/bookmycomics.js
- web-extensions/chrome/engine/datamodel.js
- web-extensions/chrome/engine/messaging.js
- web-extensions/chrome/engine/storage.js
- web-extensions/chrome/engine/ui.js
- web-extensions/chrome/entrypoint.js
- web-extensions/chrome/scripts/load-bookmarks.js
- web-extensions/chrome/sidebar.html
- web-extensions/chrome/sources.js
- web-extensions/chrome/strings.js
I fixed the extension on chrome so it works again on it (yeay!).
Other changes I made:
* I created a whole new "add bookmark" interface so now, we don't have the confusing UI that existed before anymore.
* I improved the "add button" a bit (both in design and usage): when you click on it, it brings you directly to the UI to create a new bookmark instead of just opening the list of bookmarks.
* The "add" button in the bookmarks list is now displayed all the time.
* I fixed the trash display (which blinked at light of speed when you hovered it).
> Fix chrome extension

- .circleci/config.yml
- tools/logs_codes.py
- web-extensions/chrome/strings.js
> Lint error string code

- package.json
- tests/conftest.py
- tests/func/test_001_load.py
- tests/func/test_002_sidebar_toggle.py
- tests/func/utils/bmc.py
- tests/func/utils/drivers/__init__.py
- tests/func/utils/drivers/firefox.py
This PR provides minor fixes & utilities, reworks the functional tests utilities, and validates the Sidebar Toggling mechanism, while ensuring that it's properly hidden or shown depending on the expected state.
Fixes #34
> Add Tests for the sidebar Toggling

- tools/logs_codes.py
- web-extensions/chrome/strings.js
> Fix string error codes

- web-extensions/chrome/engine/datamodel.js
- web-extensions/chrome/strings.js
Fixes #60.
To be merged after #61.
> Fix chapter page detection storage

- .circleci/config.yml
- .eslintrc.json
- .gitignore
- tests/conftest.py
- tests/func/test_002_sidebar_toggle.py
- tests/func/utils/bmc.py
- tools/functions_replacement.py
- tools/logs_codes.py
- tools/utils.py
- web-extensions/chrome/background-engine.js
- web-extensions/chrome/engine/datamodel.js
- web-extensions/chrome/engine/ui.js
- web-extensions/chrome/scripts/load-bookmarks.js
- web-extensions/chrome/sidebar.html
- web-extensions/chrome/sources.js
- web-extensions/chrome/strings.js
- web-extensions/chrome/utils.js
Fixes #51.
Not fully complete as it doesn't add the alias itself, it's just about UI and interactions.
cc @Joacchim
> Add panel for adding into existing

- tests/func/test_010_utilities.py
- tests/func/test_100_register.py
- tests/func/utils/bmc.py
Note that these new tests validate the issue from #50, which will need to be fixed to re-enable one of them.
Close #37
> Add basic registration tests

- README.md
- browsers/chrome.json
- browsers/firefox.json
- tests/conftest.py
- tests/func/test_100_register.py
- tests/func/utils/bmc.py
- tests/func/utils/drivers/chrome.py
- tests/func/utils/drivers/firefox.py
- tests/func/utils/support/mangaeden.py
- tests/func/utils/support/mangafox.py
- tests/func/utils/support/mangahere.py
- tests/func/utils/support/mangareader.py
- web-extensions/chrome/engine/datamodel.js
- web-extensions/chrome/engine/ui.js
- web-extensions/chrome/strings.js
This can be reviewed commit-per-commit (probably simpler than as a whole, since multiple subjects are part of this PR).
Essentially, I've managed to improve the success rates of the tests on my laptop with my current connection, and ended up fixing some behaviors here and there to make the single test work.
> Add EEXIST Registration test + Stabilize tests

- tests/func/test_100_register.py
- tests/func/utils/bmc.py
- tests/func/utils/support/isekaiscan.py
- tests/func/utils/support/mangafox.py
- web-extension/support/isekaiscan.js
- web-extension/support/mangafox.js
> #42 Stabilize Load test

- tests/func/test_100_register.py
- web-extension/engine/bookmycomics.js
> Registration name

- tests/func/test_100_register.py
- web-extension/scripts/load-bookmarks.js
Fixes https://github.com/BookMyComics-Developers/BookMyComics/issues/96.
> Fix comic filtering

- tests/func/test_100_register.py
- tests/func/utils/bmc.py
- web-extension/scripts/load-bookmarks.js
Fixes https://github.com/BookMyComics-Developers/BookMyComics/issues/49.
> Handle ENTER key on bookmark name input

- tests/func/test_100_register.py
- tests/func/utils/bmc.py
- tests/func/utils/support/manganato.py
- web-extension/scripts/load-bookmarks.js
> #105 stabilize manganato

- tests/func/test_100_register.py
- tests/func/utils/bmc.py
- web-extension/engine/bookmycomics.js
- web-extension/scripts/load-bookmarks.js
> Bookmark name input automatic fill with comic name

- tests/func/test_100_register.py
- web-extension/scripts/load-bookmarks.js
Fixes https://github.com/BookMyComics-Developers/BookMyComics/issues/94.
> Fix weird comic toggle behaviour

- tests/func/test_100_register.py
- web-extension/scripts/load-bookmarks.js
- web-extension/sidebar.html
Fixes https://github.com/BookMyComics-Developers/BookMyComics/issues/48.
> Highlight current comic/source

- tests/func/test_100_register.py
- tests/func/utils/bmc.py
- web-extension/scripts/load-bookmarks.js
- web-extension/sidebar.html
Fixes https://github.com/BookMyComics-Developers/BookMyComics/issues/104.
> Merge add/delete buttons into one

- tests/func/test_reader.py
- tests/func/utils/bmc.py
- web-extension/scripts/load-bookmarks.js
- web-extension/strings.js
> #93 [Tests+Bugfix] Add tracking tests & Fix sidebar update upon tracking notification

- browsers/chrome.json
- browsers/firefox.json
- tests/func/test_reader.py
- web-extension/background-engine.js
- web-extension/compat.js
- web-extension/engine/datamodel.js
- web-extension/engine/messaging.js
- web-extension/scripts/load-bookmarks.js
- web-extension/strings.js
See commit messages for details
> Rework Sidebar's "Load" handling

- tests/func/test_reader.py
- tests/func/test_register.py
- tests/func/utils/__init__.py
- tests/func/utils/bmc.py
- tests/func/utils/drivers/chrome.py
- tests/func/utils/support/isekaiscan.py
- tests/func/utils/support/mangafox.py
- tests/func/utils/support/mangakakalot.py
- tests/func/utils/support/manganato.py
- tools/logs_codes.py
- web-extension/background-engine.js
- web-extension/compat.js
- web-extension/engine/bookmycomics.js
- web-extension/engine/datamodel.js
- web-extension/engine/messaging.js
- web-extension/engine/ui.js
- web-extension/scripts/load-bookmarks.js
- web-extension/sources.js
- web-extension/strings.js
- web-extension/support/isekaiscan.js
- web-extension/support/mangafox.js
- web-extension/support/mangakakalot.js
- web-extension/support/manganato.js
This change means that any change made in any tab will automatically update the UI of all other tabs.
Still not finished: the website is not detected correctly, making the add/delete button not working as expected and the website views to not work either.
> Move handling of messages directly into the background-engine

- web-extension/engine/datamodel.js
> Trim comic name

- .circleci/config.yml
- tests/func/test_reader.py
- tests/func/test_register.py
- tests/func/utils/bmc.py
- tests/func/utils/drivers/chrome.py
- tests/func/utils/drivers/firefox.py
- tests/func/utils/support/mangafox.py
- tests/func/utils/support/mangakakalot.py
closes #134  #139 #140 #99 #38
> Improve testing by adding tests for untested scenarios

- web-extension/support/isekaiscan.js
…r prefix along with the numbers
> [Support/Isekaiscans] Fix subnumbering which was ingesting the chapter prefix along with the numbers
